### ISSUE TITLE
pip install django-pg-partitioning, error on windows 10

### ISSUE THREAD

**Issue by lidyum** [chaitin/django-pg-partitioning#10]
python verison: 3.7
pip version: 19.0.3 

`(venv) C:\django projets\api>pip install django-pg-partitioning`

Collecting django-pg-partitioning
  Using cached https://files.pythonhosted.org/packages/dd/51/1030fbdd6bc64fab059b88a59eeddba4038619c6b978c5bf02b4925e8128/django-pg-partitioning-0.11.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\\...\pip-install-yoqshn80\django-pg-partitioning\setup.py", line 11, in <module>
        long_description = f.read()
      File "C:\\....\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\encodings\cp1254.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1411: character maps to <undefined>

**Comment by virusdefender** [comment]
it's ok when i tried to install on my Python env, maybe the file is broken, try again with another network.
